services:
  fastapi_app:
    build:
      context: .
    ports:
      - "8081:8000"
    volumes:
      - sqlite_data:/usr/src/app/app.db
    container_name: fastapi_container

volumes:
  sqlite_data:
    name: sqlite_data
